### ISSUE TITLE
error when trying to execute main.py in WSL 

### ISSUE THREAD

**Issue by polyye** [ajay6763/LitMod2D_2.0_package_dist_users#10]
I am facing the following error when typing _python main.py_ in the terminal:

`user@SCI-456892:/mnt/d/LitMod2D_2.0_package_dist_users-master/GUI$` python main.py
Traceback (most recent call last):
  File "main.py", line 202, in <module>
    app=lithmod()
  File "main.py", line 88, in __init__
    tk.Tk.__init__(self, master, *args, **kwargs) # initialise tkinter
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1828, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

This is a Ubuntu 18.04 in a Windows Subsystem for Linux.

Your help is really appreciated. 
Thank you.

**Comment by ajay6763** [comment]
Hello Polyye, could you please add the solution to fix your bug so that it helps future users if they encounter it. If you have not solved it then I will get back to you over this weekend. By briefly looking at the bug it has to with the DISPLAY variable which is related to the X server.

**Comment by polyye** [comment]
Hi Ajay, thank you for your comment. That's exactly what I did and it worked. I hope to be of help.
However, I ended up installing it again on a virtual machine, to avoid future instabilities of the X server.
