### ISSUE TITLE
[Problem] Program LITMOD_V4 pause without errors when body number lager than 13

### ISSUE THREAD

**Issue by GeoSheng1998** [ajay6763/LitMod2D_2.0_package_dist_users#12]
Hi  Ajay! I am facing a problem that the model with more than 13 bodies can not be calculated successfully and the program of LITMOD_V4 is paused without errors (See figure). 
![image](https://user-images.githubusercontent.com/81002364/111861299-f26af300-8901-11eb-8400-37ca8c8bb68c.png)

**Comment by ajay6763** [comment]
Hey! , this error is most probably comming from the fact that there are some nodes in the model which do not have any material assigned to them.
To trouble shoot it I would recommend going to the node specified ( VERTICES in the above picture) and see if the corresponding node is overlapping the neighbouring bodies. 

If this does not work you can send me the following three files:
1. litmod.inp
2. bodies_GUI.out
3. bodies_GUI_envelops.out

cheers
ajay

**Comment by GeoSheng1998** [comment]
Thank you for your helpful suggestions. The problem is solved. :)
Cheers~

**Comment by ajay6763** [comment]
Perfect!
