### ISSUE TITLE
While running Lithmod2D, Gtk warning is showing

### ISSUE THREAD

**Issue by prakashncess** [ajay6763/LitMod2D_2.0_package_dist_users#20]
I could successfully installed the Lithmod2D in Linux without any Docker Image. But while running the GUI abd building model, it shows Gtk error as shown in screenshot.

Is there anyone who know the solution for this?? Thanks to Dr. Ajay for his consistent support.

Thank you!

![Gtk error](https://user-images.githubusercontent.com/36472232/134460799-87211851-96c5-4c7a-babe-7339d2da4602.png)

**Comment by ajay6763** [comment]
Please refer to the issue #3

**Comment by prakashncess** [comment]
After running #3 , I still get the error..plz see the screenshot
![Error Gtk Warning](https://user-images.githubusercontent.com/36472232/134464674-b1776fea-9e4c-412d-8ee7-41a7d3361dc3.png)

**Comment by ajay6763** [comment]
This issue is solved. See the #21  and also for standalone installation of LitMod2D_2.0.
